on: push

jobs:
  check-path:
    name: Validate Deploy Path
    runs-on: self-hosted
    environment: Production
    outputs:
      valid: ${{steps.valid.outputs.defined}}
    steps:
      - id: valid
        if: "${{ env.VALID != ''}}"
        run: echo "::set-output name=defined::true"
        env:
          VALID: ${{ secrets.DEPLOY_PATH }}
  publish:
    name: Publish
    runs-on: self-hosted
    needs: [check-path]
    environment: Production
    if: needs.check-path.outputs.valid == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Print out source contents
        run: ls ./
      - name: Prepare target folder
        run: >
            if [-d "${{secrets.DEPLOY_PATH}}]"; then
              echo "Target path exists. Should clear here."
            else 
              echo "Target path does not exist. Should create here."
            fi
      - name: Copy repo contents to target folder
        run: cp -a ./ ${{secrets.DEPLOY_PATH}}
