on: push

jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Print out contents
        run: ls ./
